/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "traffic.v:1.1-48.16" *)
module taffic(clk, rst, cur_state, count);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  (* force_downto = 32'd1 *)
  (* src = "traffic.v:0.0-0.0|traffic.v:18.11-45.18|/usr/bin/../share/yosys/techmap.v:576.21-576.22" *)
  wire [2:0] _048_;
  (* force_downto = 32'd1 *)
  (* src = "traffic.v:0.0-0.0|traffic.v:18.11-45.18|/usr/bin/../share/yosys/techmap.v:576.21-576.22" *)
  wire [3:0] _049_;
  (* src = "traffic.v:5.10-5.13" *)
  input clk;
  wire clk;
  (* src = "traffic.v:7.20-7.25" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "traffic.v:6.21-6.30" *)
  output [2:0] cur_state;
  reg [2:0] cur_state;
  (* src = "traffic.v:5.14-5.17" *)
  input rst;
  wire rst;
  assign _001_ = ~cur_state[2];
  assign _002_ = cur_state[0] | ~(cur_state[1]);
  assign _048_[0] = _001_ & ~(_002_);
  assign _003_ = cur_state[1] | cur_state[0];
  assign _004_ = cur_state[2] & ~(_003_);
  assign _005_ = _004_ | _048_[0];
  assign _006_ = cur_state[1] | ~(cur_state[0]);
  assign _007_ = _001_ & ~(_006_);
  assign _008_ = ~(_007_ | _005_);
  assign _009_ = count[0] & ~(count[1]);
  assign _010_ = count[2] | ~(count[3]);
  assign _011_ = _009_ & ~(_010_);
  assign _012_ = _011_ | ~(_004_);
  assign _013_ = _012_ & ~(_008_);
  assign _014_ = _048_[0] & ~(_011_);
  assign _015_ = count[1] & ~(count[0]);
  assign _016_ = count[2] | count[3];
  assign _017_ = _015_ & ~(_016_);
  assign _018_ = _007_ & ~(_017_);
  assign _019_ = _018_ | _014_;
  assign _000_ = _013_ & ~(_019_);
  assign _020_ = ~count[0];
  assign _021_ = _017_ | count[0];
  assign _022_ = _007_ & ~(_021_);
  assign _023_ = _011_ | count[0];
  assign _024_ = _005_ & ~(_023_);
  assign _025_ = _024_ | _022_;
  assign _049_[0] = _008_ ? _020_ : _025_;
  assign _026_ = _015_ | _009_;
  assign _027_ = _015_ ? _016_ : _009_;
  assign _028_ = _027_ & _007_;
  assign _029_ = _011_ | ~(_026_);
  assign _030_ = _005_ & ~(_029_);
  assign _031_ = _030_ | _028_;
  assign _049_[1] = _008_ ? _026_ : _031_;
  assign _032_ = ~(count[0] & count[1]);
  assign _033_ = ~(_032_ ^ count[2]);
  assign _034_ = _032_ ^ count[2];
  assign _035_ = _034_ | _017_;
  assign _036_ = _007_ & ~(_035_);
  assign _037_ = _034_ | _011_;
  assign _038_ = _005_ & ~(_037_);
  assign _039_ = _038_ | _036_;
  assign _049_[2] = _008_ ? _033_ : _039_;
  assign _040_ = count[2] & ~(_032_);
  assign _041_ = ~(_040_ ^ count[3]);
  assign _042_ = ~_041_;
  assign _043_ = _041_ | _017_;
  assign _044_ = _007_ & ~(_043_);
  assign _045_ = _041_ | _011_;
  assign _046_ = _005_ & ~(_045_);
  assign _047_ = _046_ | _044_;
  assign _049_[3] = _008_ ? _042_ : _047_;
  assign _048_[1] = ~(_007_ | _048_[0]);
  assign _048_[2] = _007_ & ~(_048_[1]);
  (* src = "traffic.v:8.3-47.8" *)
  always @(posedge clk)
    if (rst) count[0] <= 1'h0;
    else count[0] <= _049_[0];
  (* src = "traffic.v:8.3-47.8" *)
  always @(posedge clk)
    if (rst) count[1] <= 1'h0;
    else count[1] <= _049_[1];
  (* src = "traffic.v:8.3-47.8" *)
  always @(posedge clk)
    if (rst) count[2] <= 1'h0;
    else count[2] <= _049_[2];
  (* src = "traffic.v:8.3-47.8" *)
  always @(posedge clk)
    if (rst) count[3] <= 1'h0;
    else count[3] <= _049_[3];
  (* src = "traffic.v:8.3-47.8" *)
  always @(posedge clk)
    if (rst) cur_state[0] <= 1'h0;
    else if (_000_) cur_state[0] <= _048_[0];
  (* src = "traffic.v:8.3-47.8" *)
  always @(posedge clk)
    if (rst) cur_state[1] <= 1'h0;
    else if (_000_) cur_state[1] <= _048_[1];
  (* src = "traffic.v:8.3-47.8" *)
  always @(posedge clk)
    if (rst) cur_state[2] <= 1'h1;
    else if (_000_) cur_state[2] <= _048_[2];
endmodule
